### ISSUE TITLE
Decoration missing 'restore' state

### ISSUE THREAD

**Issue by UriHerrera** [nx-desktop/nx-window-deco#2]
**Describe the bug**
The window decoration is missing the restore window button when the window is maximized 

**To Reproduce**
1. Install window decoration.
2. Change it in System Settings.
3. Maximize a window.

**Expected behavior**
The window decoration provides the four window controls.

**Screenshots**
The purple button is the restore button in the Aurorae decoration.
![image](https://user-images.githubusercontent.com/3053525/81638971-3e930000-93e0-11ea-9fdc-17d5a5b4dea0.png)

**Comment by anupam-git** [comment]
This issue got fixed on 0f533e6753ec897e10634c889b5255355d0bb031
