### ISSUE TITLE
Slight glitches on the sides of the title bar

### ISSUE THREAD

**Issue by UriHerrera** [nx-desktop/nx-window-deco#3]
**Describe the bug**
When using the window decoration, there seem to be slight glitches around the title bar.

**Screenshots**

![image](https://user-images.githubusercontent.com/3053525/81644464-650b6800-93ed-11ea-89d9-3312d8ac3c3c.png)

![image](https://user-images.githubusercontent.com/3053525/81644567-9b48e780-93ed-11ea-8f14-a81f07738fc2.png)

**Comment by ademirtc** [comment]
![image](https://user-images.githubusercontent.com/12415115/108291306-12bb5c80-7160-11eb-8ba4-81a0ae07f053.png)

Fixed in commit 316823684dbbd1e57ac239d6aae96163533633b3
