### ISSUE TITLE
Unusable window buttons if using other button sizes

### ISSUE THREAD

**Issue by UriHerrera** [nx-desktop/nx-window-deco#4]
**Describe the bug**
Changing to a different size of window buttons using the settings of the decoration causes the window buttons to behave erratically.

**Expected behavior**
Changing the size of the buttons doesn't affect their behavior.

**Screenshots**
![image](https://user-images.githubusercontent.com/3053525/81644732-ecf17200-93ed-11ea-8b04-f4778c2f9731.png)

![image](https://user-images.githubusercontent.com/3053525/81644904-39d54880-93ee-11ea-8958-19ba780dfe4d.png)

**Comment by ademirtc** [comment]
![decoration](https://user-images.githubusercontent.com/12415115/108290961-709b7480-715f-11eb-891d-771c4f2652fd.gif)


Fixed in commit 316823684dbbd1e57ac239d6aae96163533633b3.
