### ISSUE TITLE
Reduce the height of title bar

### ISSUE THREAD

**Issue by UriHerrera** [nx-desktop/nx-window-deco#5]
The title bar of the window decoration is approximately 35px, which is quite significant. The height of the window decoration in the Look and Feel is 24px.

**Comment by ademirtc** [comment]
![image](https://user-images.githubusercontent.com/12415115/108290053-9889d880-715d-11eb-8faf-aa8f564026c8.png)

Fixed in commit 316823684dbbd1e57ac239d6aae96163533633b3.
